---
title: "Final Project Preliminary EDA"
output: html_notebook
authors: Evelyn Murray and Joseph Pevner
---
##Guiding Question (i.e., Research Question):
How do different aspects of determining how developed a country is (such as birth rate, population, death rate, etc.) manifest themselves in the spread of COVID-19.  Essentially, how does COVID-19 show different levels of impact on different countries?

##Data Source Exploration
1. Dataset 1 - Total COVID Cases and Deaths per Million
This dataset was accessed through the "Our World in Data" website.  Our World in Data collects their information on health from the European CDC, who reports on the progression of the COVID-19 pandemic for the whole world.  They shifted away from using data from the World Health Organization because they found many errors in reporting as well as a more significant lag time in data publishing.  This data is collected to stengthen the world's "defense against infectious diseases" and to keep the most updated tracking possible on the COVID-19 pandemic.  Each case in this dataset represents an individual day in the collection of data on COVID-19.  

Where did you find them?
Who collected/maintains them?
When & Why were they originally collected?
What does a case represent in each data source, and how many total cases are available?
What are some of the variables that you plan to use
The R Notebook should include R code chunks & output as well as narrative (bullet list is fine at this stage) as you answer these questions

Explore intuition related to the research question
Create some informative plots and summary statistics 
Describe preliminary observations and intuition about the research question

TWO Data Sources (at least)
Primary data:  This is the main data source to be used in your investigation and it MUST NOT be loaded directly from an R package (but API's are fine for example). You should have many cases (e.g., at least hundreds--preferably many thousands), many variables including a mixture of both categorical & quantitative variables.  
Other data sources: No problem for these to come from an R package--for example, the ZipGeography or ZipDemography data (from DataComputing package) might be useful when joined with primary sources as you investigate some phenomenon in the US. 
Note: Each data source should be less than 80-100MB--the maximum file size permitted in a GitHub Repo... use sampling to create a reduced version for the purpose of the project if needed as we've done occasionally in exercises and weekly activities.
